# Generated by Django 4.1.4 on 2023-01-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_alter_product_image_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='peymentMethod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
