# Generated by Django 4.1.4 on 2023-01-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_order_peymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='oreder',
            new_name='order',
        ),
    ]
